# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aafea5dd30829f54b3765da0b02fc41cca96a640c98dbf78e8e472b2d006e3afb3c048526bdc18c6714bdea39380a7ad89b3baf942c187fb61f6c2a84cd02de3

test:
  secret_key_base: 04de7bce305fb601101150a1530a3c9d36561a616d9dc1d4d35607ecdf1b65b8e4c199439d855c5b45fc0a660869993d5465c2b671e32035951b0726b36c3749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
